name: Shared PR Develop Pipeline

on:
  workflow_call:
    # (Optional) Expose the version to the calling repository
    outputs:
      vcs-version:
        description: "The extracted version from VCS"
        value: ${{ jobs.test.outputs.version }}

jobs:
  test:
    runs-on: ubuntu-latest
    # Map the step output to the job output
    outputs:
      version: ${{ steps.vcs-version.outputs.extracted-version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Remembering to keep the fix!

      - name: Simple Test
        uses: m4nh/shared-cicd/actions/python/simple-test@main
        
      - name: Build Wheel
        uses: m4nh/shared-cicd/actions/python/simple-wheel@main
        
      - name: Get VCS Version
        id: vcs-version
        uses: m4nh/shared-cicd/actions/python/vcs-version@main
        
      - name: Use the Version
        run: |
         echo "The extracted version is: ${{ steps.vcs-version.outputs.extracted-version }}"